version: '3.8'
services:
  airport:
    container_name: airport
    build:
      context: .
      target: development
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - POSTGRES_URL=${POSTGRES_URL}
    volumes:
      - ./:/app
    depends_on:
      - postgresserver

  postgresserver:
    container_name: postgres
    image: postgres:14.7
    env_file:
      - .env
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgres
      - postgres_config:/etc/postgres/conf.d
volumes:
  postgres_data:
  postgres_config:
