spring:
# Configuration data sources
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username: postgres
    password:

  #Liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: airport

# MyBatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: by.piskunou.solvdlaba.domain

jwt-secret:

