apiVersion: apps/v1
kind: Deployment
metadata:
  name: airport
spec:
  replicas: 3
  selector:
    matchLabels:
      app: airport
  template:
    metadata:
      labels:
        app: airport
    spec:
      containers:
        - name: airport
          image: cichan/airport:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: pg-configmap
                  key: POSTGRES_SCHEMA
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: pg-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: pg-configmap
                  key: POSTGRES_URL
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: airport-secrets
                  key: JWT_SECRET
