apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-configmap
data:
  POSTGRES_SCHEMA: public
  POSTGRES_DB: solvdlaba
  POSTGRES_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
