apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-configmap
data:
  POSTGRES_SCHEMA: airport
  POSTGRES_DB: solvdlaba
  POSTGRES_URL: jdbc:postgresql://postgres:5432/solvdlaba?currentSchema=airport
